### PR TITLE
supporting async functions

### PR DESCRIPTION
**Pull request by th1j5**
**NON** working first commit

Just to show where the async/await identifiers are added (until now)
I'm looking into an answer to the problem of `forEach(async function())`, because forEach is very sync orientated.

### CODE REVIEW

**Comment by ThibaultGerrier** [comment]
Yeah, syncing forEach isn't that nice. If you'd want to keep the functional style you could do an 
`await Promise.all(array.map(async function(`. But the forEach wasn't really needed in the first place. It could also just be re-written with a normal for-of or for-in loop.

Thinking more this feature, one issue with only doing awaits/async in a synchronous style (so slap awaits and asyncs everywhere) might be that performance will lack with async calls.
As an example, say you have a function making a http request for every line of a csv file. With this current approach you'd have something like this: (csv input)
```
process 1st input line
make http call
wait for response...
http response
process 2nd input line
wait for response...
http response
```

Maybe this is acceptable, idk.


This issue could probably be solved with an Promise.all (like at the top of this message) at some loop level (eg. the level of iterating over the input iterator/file lines). Looking at the code this could probably be done by re-writing the loops at `input-parser/parser.js` 110-199, by putting the if/else inside the loop and changing the for loop to an 
```javascript
const indexes = [...Array(iteratorNumber).keys()] // array from 0 to iteratorNumber
await Promise.all(is.map(async(indexes ){
  if(){}elseif{}else{}
}));
```
and also chaning that inner forEach on 120 to an `await Promise.all(nodes.map(async (temp) => {`

The example would then change to something more like this:
```
process 1st input line
make http call
process 2nd input line
make http call
wait for response... // notice both http requests waiting at the same time
wait for response...
http response
http response
```

Of course now there is the issue that starting lots of http calls at the same time might be problematic (load for receiving server...), which didn't happen in the first scenario.

Not sure what would be best, or how to fix the 2nd problem.

**Comment by th1j5** [comment]
If you run the new test case, you will see it still fails.  
I don't really know what's happening, but it's happening in the case statement in functions.js.  

Some sources which can be useful:

https://stackoverflow.com/questions/40185880/making-a-promise-work-inside-a-javascript-switch-case

Also the is something in MDN about split execution flow which might or might not be in effect (it's chinese to me).
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#Description

I changed both 'forEach' to a plain 'for ( of )', because both times the order of execution was important. (I didn't always know why, but the test cases helped me :)
https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop

**Comment by ThibaultGerrier** [comment]
Okay, fixed the code, the issue was an async forEach, rewriting that in a for of loop fixed the job

**Comment by ThibaultGerrier** [comment]
Did a bit of performance testing with this version and the current v1.6.1.
Using the mapping of tests/performanceTest.js (smallish mapping with 2 triplemap and 1 join, but large input files), I have found that this version performs on average at about 92% of the speed of the original (or 8% slower). 
More than i had thought, but I think this is acceptable. Performance could always be improved at a later date.

**Comment by th1j5** [comment]
Ok,
Thank you for finishing this, becoming a true async javascript wizard will be for a later date.

If the performance hit is acceptable for you, than I think nothing stops us from merging this.

Thank you for upgrading RocketRML, I will be able to use it!

Greetings

**Comment by ThibaultGerrier** [comment]
published in v1.7.0

**Pull request merged**
